# Generated by Django 4.1.4 on 2023-01-26 18:09

import app.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('item_id', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('item_name', models.TextField()),
                ('item_description', models.TextField(blank=True, default=None, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='PurchaseOrderItem',
            fields=[
                ('itemID', models.AutoField(primary_key=True, serialize=False)),
                ('itemName', models.CharField(max_length=10)),
                ('itemQtyNeeded', models.IntegerField()),
                ('itemPricePerUnit', models.DecimalField(decimal_places=2, max_digits=10)),
                ('itemPrice', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='Purchaser',
            fields=[
                ('purchaserID', models.AutoField(primary_key=True, serialize=False)),
                ('purchaserAddress', models.CharField(max_length=50)),
                ('purchaserContact', models.BigIntegerField()),
                ('purchaserName', models.CharField(max_length=30)),
                ('purchaserCompanyName', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Vendor',
            fields=[
                ('vendorID', models.AutoField(primary_key=True, serialize=False)),
                ('vendorName', models.CharField(max_length=20)),
                ('vendorContact', models.BigIntegerField()),
                ('vendorAddress', models.CharField(max_length=50)),
                ('vendorCompanyName', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='QuotationProduct',
            fields=[
                ('productID', models.AutoField(primary_key=True, serialize=False)),
                ('productName', models.CharField(max_length=30)),
                ('productQtyProvided', models.IntegerField()),
                ('productPricePerUnit', models.DecimalField(decimal_places=2, max_digits=10)),
                ('productTotalPrice', models.DecimalField(decimal_places=2, max_digits=10)),
                ('purchaserID', models.ForeignKey(null=True, on_delete=models.SET(app.models.get_purchaserID), to='app.purchaser')),
                ('vendorID', models.ForeignKey(on_delete=models.SET(app.models.get_vendorID), to='app.vendor')),
            ],
        ),
        migrations.CreateModel(
            name='Quotation',
            fields=[
                ('quotationID', models.AutoField(primary_key=True, serialize=False)),
                ('quotationStatus', models.CharField(choices=[('PENDING', 'pending'), ('APPROVED', 'approved')], default='PENDING', max_length=10)),
                ('quotationDate', models.DateField(max_length=10)),
                ('quotationValidDate', models.DateField(max_length=10)),
                ('totalPrice', models.DecimalField(decimal_places=2, max_digits=10)),
                ('isPO', models.BooleanField(default=False)),
                ('productID', models.ManyToManyField(null=True, to='app.quotationproduct')),
                ('purchaserID', models.ForeignKey(on_delete=models.SET(app.models.get_purchaserID), to='app.purchaser')),
                ('vendorID', models.ForeignKey(on_delete=models.SET(app.models.get_vendorID), to='app.vendor')),
            ],
        ),
        migrations.CreateModel(
            name='PurchaseOrder',
            fields=[
                ('poID', models.AutoField(primary_key=True, serialize=False)),
                ('poValidDate', models.DateField(max_length=10)),
                ('poApprovalStatus', models.CharField(choices=[('PENDING', 'pending'), ('APPROVED', 'approved'), ('REJECTED', 'rejected')], default='PENDING', max_length=10)),
                ('poDate', models.DateField(max_length=10)),
                ('orderSubtotal', models.DecimalField(decimal_places=2, max_digits=10)),
                ('itemID', models.ManyToManyField(blank=True, to='app.purchaseorderitem')),
                ('purchaserID', models.ForeignKey(on_delete=models.SET(app.models.get_purchaserID), to='app.purchaser')),
                ('vendorID', models.ForeignKey(on_delete=models.SET(app.models.get_vendorID), to='app.vendor')),
            ],
        ),
    ]
